package com.babynameplus.enums;

/**
 * Created by spio10 on 2017-06-04.
 */
public class Origin {

    public static final String[] FEMALE_ORIGINS = {"angielskie",
            "arabskie",
            "aramejskie",
            "białoruskie",
            "brytyjskie",
            "celtyckie",
            "czeskie",
            "francuskie",
            "germańskie",
            "greckie",
            "greckie",
            "grecko - łacińskie",
            "hebrajskie",
            "hiszpańskie",
            "litewskie",
            "łacińskie",
            "macedońskie",
            "niemieckie",
            "nieznane",
            "norweskie",
            "perskie",
            "polskie",
            "romańsko-germańskie",
            "rosyjskie",
            "rzymskie",
            "skandynawskie",
            "słowiańskie",
            "staropolskie",
            "starorosyjskie",
            "starosaksońskie",
            "węgierskie",
            "włoskie" };
    public static final String[] MALE_ORIGINS = {
            "aramejskie",
            "babilońskie",
            "celtyckie",
            "czeskie",
            "egipskie",
            "francuskie",
            "germańskie",
            "greckie",
            "grecko - łacińskie",
            "hebrajskie",
            "hiszpańskie",
            "hiszpańsko - portugalskie",
            "litewskie",
            "łaciński",
            "łacińskie",
            "mongolskie",
            "niemieckie",
            "perskie",
            "polskie",
            "saksońskie",
            "semickie",
            "skandynawskie",
            "słowiańskie",
            "staroniemieckie",
            "staroperskie",
            "staropolskie",
            "starosaksońskie",
            "staroskandynawskie",
            "włoskie" };
}
