package com.babynameplus.enums;

/**
 * Created by spio10 on 2017-06-04.
 */
public class Origin {

    public static final String[] FEMALE_ORIGINS = {"angielskie",
            "arabskie",
            "aramejskie",
            "bia³oruskie",
            "brytyjskie",
            "celtyckie",
            "czeskie",
            "francuskie",
            "germañskie",
            "greckie",
            "greckie",
            "grecko - ³aciñskie",
            "hebrajskie",
            "hiszpañskie",
            "litewskie",
            "³aciñskie",
            "macedoñskie",
            "niemieckie",
            "nieznane",
            "norweskie",
            "perskie",
            "polskie",
            "romañsko-germañskie",
            "rosyjskie",
            "rzymskie",
            "skandynawskie",
            "s³owiañskie",
            "staropolskie",
            "starorosyjskie",
            "starosaksoñskie",
            "wêgierskie",
            "w³oskie" };
    public static final String[] MALE_ORIGINS = {
            "aramejskie",
            "babiloñskie",
            "celtyckie",
            "czeskie",
            "egipskie",
            "francuskie",
            "germañskie",
            "greckie",
            "grecko - ³aciñskie",
            "hebrajskie",
            "hiszpañskie",
            "hiszpañsko - portugalskie",
            "litewskie",
            "³aciñski",
            "³aciñskie",
            "mongolskie",
            "niemieckie",
            "perskie",
            "polskie",
            "saksoñskie",
            "semickie",
            "skandynawskie",
            "s³owiañskie",
            "staroniemieckie",
            "staroperskie",
            "staropolskie",
            "starosaksoñskie",
            "staroskandynawskie",
            "w³oskie" };
}
